apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namePrefix: dev-

images:
- name: kind-registry:5000/app-backend
  newName: nginx
  newTag: 1.26.3


configMapGenerator:
  - envs:
      - .env.dev
    name: app-backend-env
