apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namePrefix: dev-

images:
- name: linomota0/app-backend
  newName: linomota0/app-backend
  newTag: v20


configMapGenerator:
  - envs:
      - .env.dev
    name: app-backend-env
